import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {readFile} from 'node:fs/promises';
import proto from 'onnx-proto';
test('shipped ONNX is a valid self-contained color detector',async()=>{const data=await readFile(new URL('../public/models/sample-symbols.onnx',import.meta.url));const model=proto.onnx.ModelProto.decode(data);assert.equal(model.graph.input[0].name,'pixels');assert.equal(model.graph.output[0].name,'distances');assert.ok(data.length<10000);});
test('model failure produces an error without color or example substitute results',async()=>{
 const messages=[];globalThis.self={postMessage:m=>messages.push(m),navigator:{}};
 const originalFetch=globalThis.fetch;globalThis.fetch=async()=>new Response('missing',{status:404});
 try{await import('../src/engine.worker.js?failure-test');await self.onmessage({data:{width:8,height:8,pixels:new Uint8Array(8*8*4).buffer,mode:'custom',modelUrl:'/missing.onnx',labels:['Fixture']}});assert.ok(messages.some(m=>m.type==='error'));assert.ok(!messages.some(m=>m.type==='done'));}finally{globalThis.fetch=originalFetch;}
});
test('actual sample pixels produce all 14 symbols and pipe lengths without AI',async()=>{const {data,info}=await sharp(new URL('../public/samples/residence-plumbing.png',import.meta.url).pathname.replace(/^\/(\w:)/,'$1')).ensureAlpha().raw().toBuffer({resolveWithObject:true});const messages=[];globalThis.self={postMessage:m=>messages.push(m)};await import('../src/engine.worker.js');await self.onmessage({data:{width:info.width,height:info.height,pixels:data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),mode:'heuristic'}});const done=messages.find(m=>m.type==='done');assert.ok(done,JSON.stringify(messages));assert.equal(done.points.length,14);assert.equal(done.points.filter(p=>p.label==='Fixture').length,8);assert.equal(done.points.filter(p=>p.label==='Valve').length,2);assert.equal(done.points.filter(p=>p.label==='Floor drain').length,2);assert.equal(done.points.filter(p=>p.label==='Hydrant').length,1);assert.equal(done.points.filter(p=>p.label==='Cleanout').length,1);assert.ok(done.runs.length>=10);assert.deepEqual([...new Set(done.runs.map(r=>r.group))].sort(),['Cold','Hot','Waste']);assert.ok(done.elapsed<20);console.log(`Sample fallback: ${done.points.length} points, ${done.runs.length} segments, ${done.elapsed.toFixed(2)}s`);});
