import {POINT_CLASSES,POINT_COLORS,PIPE_COLORS,PIPE_SYSTEMS,tiles,dedupe,decodeYolo} from './core.js';
const post=(type,data)=>self.postMessage({type,...data});
const colorDistance=(r,g,b,c)=>Math.abs(r-c[0])+Math.abs(g-c[1])+Math.abs(b-c[2]);
function components(mask,w,h,label){const found=[];const queue=new Int32Array(w*h);for(let p=0;p<mask.length;p++){if(mask[p]!==label)continue;let head=0,tail=1,sumX=0,sumY=0;queue[0]=p;mask[p]=0;while(head<tail){const i=queue[head++],x=i%w,y=Math.floor(i/w);sumX+=x;sumY+=y;for(const j of [x>0?i-1:-1,x<w-1?i+1:-1,y>0?i-w:-1,y<h-1?i+w:-1])if(j>=0&&mask[j]===label){mask[j]=0;queue[tail++]=j;}}if(tail>=12&&tail<3000)found.push({x:sumX/tail,y:sumY/tail,label:POINT_CLASSES[label-1]});}return found;}
function lines(mask,w,h,c){const output=[];for(const vertical of [false,true]){const extent=vertical?h:w,rows=vertical?w:h,spans=[];for(let row=0;row<rows;row++){let start=-1,gap=0;for(let pos=0;pos<=extent;pos++){const hit=pos<extent&&mask[vertical?pos*w+row:row*w+pos]===c;if(hit){if(start<0)start=pos;gap=0;}else if(start>=0){gap++;if(gap>2||pos===extent){const end=pos-gap;if(end-start>=28){const prev=spans.findLast(s=>row-s.last<=3&&Math.abs(s.start-start)<8&&Math.abs(s.end-end)<8);if(prev){prev.last=row;prev.count++;}else spans.push({start,end,row,last:row,count:1});}start=-1;gap=0;}}}}for(const s of spans)if(s.count>=2&&s.count<=12){const mid=(s.row+s.last)/2;output.push({group:PIPE_SYSTEMS[c-1],points:vertical?[{x:mid,y:s.start},{x:mid,y:s.end}]:[{x:s.start,y:mid},{x:s.end,y:mid}]});}}return output;}
self.onmessage=async({data})=>{let session;const started=performance.now();try{const {width:w,height:h,pixels,mode,modelUrl,labels}=data;const rgba=new Uint8ClampedArray(pixels),mask=new Uint8Array(w*h),pipeMask=new Uint8Array(w*h),jobs=tiles(w,h);if(jobs.length>36)throw new Error('Sheet exceeds the 36-tile processing limit.');let backend='Heuristic',ort;let useModel=mode!=='heuristic';
 if(useModel)try{post('progress',{progress:3,message:'Loading on-device model…'});ort=await import('onnxruntime-web/webgpu');ort.env.wasm.wasmPaths='/ort/';ort.env.wasm.numThreads=1;const url=mode==='custom'?modelUrl:'/models/sample-symbols.onnx';if(!url)throw new Error('Provide an ONNX model URL.');
 const response=await fetch(url,{signal:AbortSignal.timeout(25000)});if(!response.ok)throw new Error('Model download failed: '+response.status);const declared=Number(response.headers.get('content-length'));if(declared>40*1024*1024)throw new Error('Model exceeds the 40 MB limit.');const reader=response.body.getReader(),chunks=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>40*1024*1024){await reader.cancel();throw new Error('Model exceeds the 40 MB limit.');}chunks.push(value);}const bytes=new Uint8Array(size);let at=0;for(const chunk of chunks){bytes.set(chunk,at);at+=chunk.length;}
 try{if(!self.navigator.gpu)throw new Error('WebGPU unavailable');session=await ort.InferenceSession.create(bytes,{executionProviders:['webgpu']});backend='WebGPU';}catch(e){post('warning',{message:'WebGPU unavailable or unsupported; using WASM CPU. '+e.message});session=await ort.InferenceSession.create(bytes,{executionProviders:['wasm']});backend='WASM CPU';}
 }catch(e){useModel=false;backend='Heuristic';post('warning',{message:'Model unavailable; color heuristics are active. '+e.message});}
 let detected=[];for(let t=0;t<jobs.length;t++){if(performance.now()-started>150000)throw new Error('Processing reached its 150-second work budget. Use a smaller sheet or manual tools.');const tile=jobs[t];post('progress',{progress:8+Math.round(t/jobs.length*67),message:`${backend} · tile ${t+1} of ${jobs.length}`,backend});let scores;
 if(useModel){const custom=mode==='custom',input=new Float32Array(custom?3*640*640:tile.width*tile.height*3);if(custom)input.fill(1);for(let y=0;y<tile.height;y++)for(let x=0;x<tile.width;x++){const i=((tile.y+y)*w+tile.x+x)*4;for(let c=0;c<3;c++)input[custom?c*640*640+y*640+x:(y*tile.width+x)*3+c]=rgba[i+c]/255;}
 try{const results=await session.run({[session.inputNames[0]]:new ort.Tensor('float32',input,custom?[1,3,640,640]:[tile.width*tile.height,3])});const out=results[session.outputNames[0]];if(custom)detected.push(...decodeYolo(out.data,out.dims,labels,tile).filter(p=>p.x>=tile.x&&p.x<tile.x+tile.width&&p.y>=tile.y&&p.y<tile.y+tile.height));else scores=new Float32Array(out.data);for(const v of Object.values(results))v.dispose();}catch(e){useModel=false;backend='Heuristic';post('warning',{message:'Inference failed; remaining tiles use color heuristics. '+e.message});}}
 for(let y=0;y<tile.height;y++)for(let x=0;x<tile.width;x++){const p=(tile.y+y)*w+tile.x+x,i=p*4,r=rgba[i],g=rgba[i+1],b=rgba[i+2];if(mode!=='custom'||!useModel){for(let c=0;c<5;c++)if(scores?scores[(y*tile.width+x)*5+c]<.22:colorDistance(r,g,b,POINT_COLORS[c])<55){mask[p]=c+1;break;}}for(let c=0;c<6;c++)if(colorDistance(r,g,b,PIPE_COLORS[c])<38){pipeMask[p]=c+1;break;}}
 }
 post('progress',{progress:80,message:'Finding symbols and tracing pipe centerlines…'});for(let c=1;c<=5;c++)detected.push(...components(mask,w,h,c));const runs=[];for(let c=1;c<=6;c++)runs.push(...lines(pipeMask,w,h,c));
 post('done',{points:dedupe(detected),runs,backend,elapsed:(performance.now()-started)/1000});
 }catch(e){post('error',{message:e.message});}finally{if(session)await session.release();}};
