import './style.css';
import './workflow.css';
import './review.css';
import {extractPdfEvidence,analyzePdf} from './pdf-analysis.js';
import {explainItem,explanationNote} from './explanations.js';
import {createWorkflow} from './workflow.js';
let workflow;
import {SYSTEMS,POINT_CLASSES,makeScale,quantity,report,csv,newItem,pixelLength} from './core.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name)=>({select:'↖',calibrate:'↔',count:'⊕',length:'⌁',undo:'↶',upload:'↥',download:'↓',settings:'⚙'}[name]||name);
let state={doc:null,scale:null,items:[],outcomes:['count','length']},selected=null,selectedVertex=null,tool='select',draft=[],history=[],zoom=1,worker=null,runTimer=null,elapsedTimer=null,running=false,pdf=null,pdfPage=1,drag=null,errors=[];
const raster=document.createElement('canvas');
$('#app').innerHTML=`
<aside class="rail"><a class="brand-icon" href="/" aria-label="ArchiQuant home">A<span>Q</span></a><button class="rail-button active" title="Takeoff workspace" id="workspace-nav">▧</button><button class="rail-button" title="Select scope" id="scope-nav">▦</button><div class="rail-bottom"><span class="private-icon" title="Plans stay on this device">⌑</span><span class="avatar">AQ</span></div></aside>
<div class="shell"><header><div><div class="brand">ArchiQuant<span class="beta">LOCAL WORKSPACE</span></div><div class="breadcrumb">Projects <span>/</span> <strong id="project-name">Untitled takeoff</strong></div></div><div class="header-actions"><span class="privacy">◈ &nbsp; Files stay on your device</span><button class="button" id="sample">Load sample</button><button class="button primary" id="upload">${icon('upload')} Upload plan</button><input type="file" id="file" accept="application/pdf,image/png,image/jpeg,image/webp" hidden></div></header>
<div class="project-bar"><div><span class="eyebrow">QUANTITY TAKEOFF</span><h1>Every line. Accounted for.</h1></div><div class="project-actions"><button class="scope-chip" id="scope-button">◉ &nbsp; Plumbing <span>⌄</span></button><button class="button" id="settings">${icon('settings')} Detection settings</button></div></div>
<nav class="steps" aria-label="Takeoff steps"><span id="step-upload"><b>1</b> Add drawing</span><i></i><span id="step-scale"><b>2</b> Set scale</span><i></i><span id="step-run"><b>3</b> Detect & review</span><i></i><span id="step-export"><b>4</b> Export quantities</span><div class="step-note">YOUR JUDGMENT. ASSISTED.</div></nav>
<div id="notice" class="notice" role="status"><span>Start with your drawing, or explore the included residential sample.</span></div>
<main class="workbench"><section class="drawing-panel"><div class="panel-heading"><div><span class="live-dot"></span><strong id="sheet-name">Drawing workspace</strong><span id="sheet-meta" class="muted">PDF / PNG / JPG</span></div><div class="view-actions"><select id="page" aria-label="PDF page" hidden></select><button id="zoom-out" aria-label="Zoom out">−</button><span id="zoom-label">100%</span><button id="zoom-in" aria-label="Zoom in">+</button><button id="fit" title="Fit drawing">Fit</button></div></div>
<div class="drawing-toolbar"><div class="tools">${['select','calibrate','count','length'].map(t=>`<button data-tool="${t}" title="${t==='select'?'Select and move geometry':t}" class="tool ${t==='select'?'active':''}"><span>${icon(t)}</span> ${t[0].toUpperCase()+t.slice(1)}</button>`).join('')}</div><div><button class="tool" id="undo" title="Undo last edit">↶</button><button class="tool" id="toggle-overlay" title="Toggle overlay">◉</button></div></div>
<div class="canvas-viewport" id="viewport"><div id="empty" class="empty"><div class="empty-blueprint">⌑</div><span class="eyebrow">FROM DRAWING TO QUANTITIES</span><h2>Your next takeoff starts here.</h2><p>Drop a plumbing plan to start measuring.<br>PDF, PNG, JPG or WebP · up to 30 MB</p><button class="button primary" id="empty-upload">Choose a drawing <span>↗</span></button><button class="text-button" id="empty-sample">Try the residential sample →</button><div class="sample-preview"><img src="/samples/residence-plumbing.png" alt="Preview of the included residential plumbing sample"><span>P-101 &nbsp; RESIDENTIAL SAMPLE</span></div></div><div id="sheet-wrap" hidden><img id="sheet-image" alt="Uploaded construction drawing" draggable="false"><svg id="overlay" xmlns="http://www.w3.org/2000/svg" aria-label="Editable takeoff drawing"></svg></div></div>
<div class="drawing-footer"><span id="scale-status">↔ &nbsp; Scale not calibrated</span><span id="tool-hint">Select a drawing to begin</span><button class="text-button" id="finish" hidden>Finish line ✓</button></div><div class="legend">${Object.entries(SYSTEMS).filter(([s])=>['Cold','Hot','Waste','Fixtures'].includes(s)).map(([s,c])=>`<span><i style="background:${c}"></i>${s}</span>`).join('')}<span class="legend-note">Drag selected points to adjust</span></div></section>
<aside class="worksheet-panel"><div class="worksheet-heading"><div><span class="eyebrow">LIVE WORKSHEET</span><h2>Takeoff quantities <span id="row-count">0</span></h2></div><button class="text-button" id="add-item">+ Add</button></div><div class="summary"><div><span>Point items</span><strong id="count-total">0 <small>ea</small></strong></div><div><span>Pipe length</span><strong id="length-total">— <small>m</small></strong></div></div>
<div class="run-box"><div class="run-options"><label><input type="checkbox" id="ai-enabled" checked> Enable automatic calculation</label><span id="backend">On-device</span></div><button class="button primary run-button" id="run" disabled>✧ &nbsp; Run takeoff</button><div id="progress-wrap" hidden><progress id="progress" max="100" value="0"></progress><div><span id="progress-text">Preparing…</span><button class="text-button" id="cancel">Cancel</button></div></div><p id="run-help">Calibrate the drawing before running detection.</p></div>
<div class="worksheet-filter"><span>ITEM / GROUP</span><span>QUANTITY</span></div><div id="rows" class="rows"><div class="rows-empty"><span>⌁</span><h3>A clear view of your quantities.</h3><p>Detected and manually added items appear here. Select a row to inspect its geometry.</p></div></div><div id="editor" class="item-editor" hidden></div>
<div class="export-bar"><span id="review-status">Review before exporting</span><div><button class="button" id="export-csv" disabled>↓ CSV</button><button class="button primary" id="export-json" disabled>↓ JSON report</button></div></div></aside></main>
<footer class="app-footer"><span>ARCHIQUANT <b>/</b> RESIDENTIAL PLUMBING</span><span>Plan lengths only · verify symbols, systems & vertical runs</span><button class="text-button" id="warnings">Activity & notices <span id="warning-count">0</span></button></footer></div>
<dialog id="scope-dialog"><div class="dialog-top"><span class="eyebrow">CALCULATION LIBRARY</span><button class="close" data-close="scope-dialog" aria-label="Close">×</button></div><h2>What are you measuring?</h2><p>Choose the scope and the quantities you need.</p><div class="scope-card selected"><span class="scope-symbol">⌁</span><div><h3>Plumbing</h3><p>Residential fixtures, accessories and pipe runs.</p></div><span>✓</span></div><div class="outcomes"><label><input type="checkbox" id="out-count" checked> Point items <small>Fixtures, valves, drains, hydrants, cleanouts</small></label><label><input type="checkbox" id="out-length" checked> Pipe lengths <small>Cold, hot, soil, waste, vent and fire</small></label></div><div class="future-scopes"><div>▧ &nbsp; Electrical <small>Not available</small></div><div>▥ &nbsp; Structural <small>Not available</small></div></div><button class="button primary full" id="scope-continue">Continue with plumbing →</button></dialog>
<dialog id="scale-dialog"><div class="dialog-top"><span class="eyebrow">TWO-POINT CALIBRATION</span><button class="close" data-close="scale-dialog" aria-label="Close">×</button></div><h2>Set the real-world distance.</h2><p id="scale-description"></p><div class="input-row"><label>Distance<input id="real-distance" type="number" min="0.001" step="any" value="10"></label><label>Unit<select id="scale-unit"><option value="m">Meters</option><option value="ft">Feet</option></select></label></div><p class="small">Use a printed dimension. Calibration is specific to this page and image resolution.</p><button class="button primary full" id="save-scale">Confirm scale</button></dialog>
<dialog id="settings-dialog"><div class="dialog-top"><span class="eyebrow">ON-DEVICE DETECTION</span><button class="close" data-close="settings-dialog" aria-label="Close">×</button></div><h2>Detection settings</h2><label>Detector<select id="model-mode"><option value="auto">Automatic · choose from drawing evidence</option><option value="pdf">PDF labels + CAD layers</option><option value="sample">Test sample-symbol ONNX</option><option value="heuristic">Test color rules only</option><option value="custom">Custom YOLO ONNX (640 × 640)</option></select></label><p class="small">Automatic mode uses PDF labels and named pipe layers where available. The bundled tiny model recognizes the sample's colored symbols. It is not a trained plumbing detector. Pipe suggestions use colored, straight-line geometry. Always review results; monochrome plans may require manual tracing.</p><div id="custom-settings" hidden><label>ONNX URL<input id="model-url" placeholder="/models/plumbing.onnx"></label><label>Class labels, in model order<input id="model-labels" value="Fixture,Valve,Floor drain,Hydrant,Cleanout"></label><p class="small">Requires a compatible YOLO detect export, NCHW input and raw [1, 4+C, N] output. URLs must allow browser access; maximum 40 MB.</p></div><p class="small">WebGPU → WASM CPU. Model failure stops detection; it never substitutes example quantities. Up to 36 overlapping tiles. A 180-second watchdog stops stalled inference.</p><button class="button primary full" data-close="settings-dialog">Save settings</button></dialog>
<dialog id="activity-dialog"><div class="dialog-top"><span class="eyebrow">SESSION ACTIVITY</span><button class="close" data-close="activity-dialog" aria-label="Close">×</button></div><h2>Notices & processing</h2><div id="activity-list"></div><button class="button" id="clear-session">Clear saved session</button></dialog>
<dialog id="replace-dialog"><h2>Replace this drawing?</h2><p>Your current measurements will be cleared. Export them first if you need a copy.</p><div class="input-row"><button class="button" id="replace-cancel">Keep current</button><button class="button primary" id="replace-confirm">Replace drawing</button></div></dialog>`;
function notice(message,warning=false){$('#notice').hidden=!message;$('#notice').classList.toggle('warning',warning);$('#notice').firstElementChild.textContent=message;}
function log(message,warning=true){errors.push({time:new Date().toLocaleTimeString(),message,warning});$('#warning-count').textContent=errors.length;notice(message,warning);}
function save(){workflow?.persist(state);try{localStorage.setItem('archiquant-v1',JSON.stringify(state));}catch(e){if(!errors.some(x=>x.message.startsWith('Session storage')))log('Session storage is full or unavailable. Keep this tab open and export your report.');}}
function checkpoint(){history.push(JSON.stringify(state));if(history.length>30)history.shift();}
function mutate(fn){checkpoint();fn();save();render();}
function setTool(t){if(!state.doc)return notice('Load a drawing first.',true);if(running)return;tool=t;draft=[];document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#tool-hint').textContent=({select:'Select a row or marker; drag its handles to edit',calibrate:state.doc.sample?'Click the two endpoints of the 10 m dimension':'Click two ends of a known dimension',count:'Click drawing to place a point item',length:'Click to trace a pipe; Enter to finish · Esc to cancel'})[t];$('#finish').hidden=t!=='length';renderOverlay();}
function render(){workflow?.refresh();for(const k of ['count','length'])$('#out-'+k).checked=state.outcomes.includes(k);const counts=state.items.filter(i=>i.kind==='count').reduce((s,i)=>s+quantity(i,state.scale),0),lengths=state.items.filter(i=>i.kind==='length').reduce((s,i)=>s+quantity(i,state.scale),0);$('#count-total').innerHTML=`${counts} <small>ea</small>`;$('#length-total').innerHTML=`${state.scale?lengths.toFixed(2):'—'} <small>m</small>`;$('#row-count').textContent=state.items.length;$('#scale-status').textContent=state.scale?`↔  Calibrated · ${state.scale.pixelsPerMeter.toFixed(2)} px/m`:'↔  Scale not calibrated';$('#run').disabled=!state.doc||!state.scale||running||!$('#ai-enabled').checked;$('#run-help').textContent=!$('#ai-enabled').checked?'Manual mode: use Count and Length on the drawing.':!state.scale?'Calibrate the drawing before running detection.':$('#model-mode').value==='custom'?'Custom model suggestions need review.':$('#model-mode').value==='pdf'||($('#model-mode').value==='auto'&&(state.doc?.pdfEvidence||state.doc?.realPlan))?'Read actual PDF labels and named CAD pipe layers. Unidentified items remain unmeasured.':state.doc?.sample?'Sample-symbol detector · colored demonstration only.':'No general plumbing model is bundled. Monochrome images may return no results.';for(const id of ['export-csv','export-json'])$('#'+id).disabled=!state.scale||!state.items.length||running;$('#review-status').textContent=state.items.length?'Draft quantities · review all items':'Review before exporting';$('#step-upload')?.classList.toggle('done',!!state.doc);$('#step-scale')?.classList.toggle('done',!!state.scale);$('#step-run')?.classList.toggle('done',!!state.items.length);
 $('#rows').innerHTML=state.items.length?`<table class="quantity-table" aria-label="Takeoff quantity table"><thead><tr><th>ITEM / GROUP / SOURCE</th><th>QTY</th><th>UNIT</th></tr></thead><tbody>${state.items.map(i=>`<tr class="item-row ${selected===i.id?'selected':''}" data-id="${i.id}" tabindex="0" aria-selected="${selected===i.id}"><td><span class="item-glyph" style="--item-color:${SYSTEMS[i.group]||SYSTEMS.Pipe}">${i.kind==='count'?'⊕':'⌁'}</span><span class="item-copy"><strong>${esc(i.label||'Unnamed item')}</strong><small>${esc(i.group)} <em>${i.source==='AI'?(i.analysis?.method?.startsWith('PDF')?'PDF RULES · REVIEW':'DETECTED · REVIEW'):'MANUAL'}</em></small></span></td><td class="quantity-cell">${i.kind==='length'&&!state.scale?'—':quantity(i,state.scale).toFixed(i.kind==='count'?0:2)}</td><td class="unit-cell">${i.kind==='count'?'ea':'m'}</td></tr>`).join('')}</tbody></table>`:`<div class="rows-empty"><span>⌁</span><h3>No measurements yet.</h3><p>Use Count or Length to add measurements on the drawing, or return to Calculate.</p></div>`;
 $('#rows').querySelectorAll('[data-id]').forEach(b=>{const choose=()=>{selected=b.dataset.id;selectedVertex=null;setTool('select');render();scrollSelectedRow();workflow?.focusDrawing(state.items.find(i=>i.id===selected).geom.points);};b.onclick=choose;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};});renderEditor();renderOverlay();}
function scrollSelectedRow(){const row=$('#rows [data-id="'+selected+'"]');if(!row)return;const parent=$('#rows'),r=row.getBoundingClientRect(),box=parent.getBoundingClientRect();if(r.top<box.top+45)parent.scrollTop+=r.top-box.top-45;else if(r.bottom>box.bottom)parent.scrollTop+=r.bottom-box.bottom;}
function focusPoints(points,forceZoom){if(!state.doc||!points.length)return;const xs=points.map(p=>p.x),ys=points.map(p=>p.y),left=Math.min(...xs),right=Math.max(...xs),top=Math.min(...ys),bottom=Math.max(...ys),v=$('#viewport'),base=Math.max(1,v.clientWidth-64),fit=Math.min(base/Math.max(right-left,150),(v.clientHeight-64)/Math.max(bottom-top,150))*state.doc.width/base*.7;setZoom(forceZoom||Math.max(1,Math.min(6,fit)));requestAnimationFrame(()=>{const factor=$('#sheet-wrap').getBoundingClientRect().width/state.doc.width;v.scrollTo({left:(left+right)/2*factor-v.clientWidth/2+32,top:(top+bottom)/2*factor-v.clientHeight/2+32,behavior:'instant'});});}
function renderEditor(){const focus=document.activeElement, focusId=focus?.id, cursor=focus?.selectionStart;const item=state.items.find(i=>i.id===selected);$('#editor').hidden=!item;if($('#inspector-empty'))$('#inspector-empty').hidden=!!item;if($('#element-evidence')){$('#element-evidence').hidden=!item;if(item){const a=explainItem(item,state.scale);$('#element-evidence').innerHTML=`<span class="method-pill">${esc(a.method)}</span><h3>${esc(item.label)}</h3><dl><dt>Interpreted as</dt><dd>${esc(a.classification)}</dd><dt>Why this result</dt><dd>${esc(a.evidence)}</dd><dt>Measurement</dt><dd>${esc(a.measurement)}</dd><dt>Confidence</dt><dd>${esc(a.confidence)}</dd></dl><div class="review-caution">${esc(a.limitations)}${a.edited?' Manually edited after detection; original evidence is retained.':''}</div>`;}}if(!item)return;$('#editor').innerHTML=`<div class="editor-title"><strong>Properties</strong><button class="text-button danger" id="delete-row">Delete</button></div><div class="input-row"><label>Label<input id="edit-label" value="${esc(item.label)}"></label><label>Group<input id="edit-group" list="groups" value="${esc(item.group)}"><datalist id="groups">${Object.keys(SYSTEMS).map(s=>`<option>${s}</option>`).join('')}</datalist></label></div><div class="input-row"><label>Quantity (${item.kind==='count'?'ea':'m'})<input id="edit-qty" type="number" min="${item.kind==='count'?1:.01}" step="${item.kind==='count'?1:.01}" value="${quantity(item,state.scale).toFixed(item.kind==='count'?0:2)}" ${!state.scale&&item.kind==='length'?'disabled':''}></label><label>Source<input value="${item.source==='AI'&&item.analysis?.method?.startsWith('PDF')?'Program · PDF rules':item.source}" disabled></label></div><label>Review notes<textarea id="edit-note" rows="2" placeholder="Size, specification, exclusions…">${esc(item.note)}</textarea></label><div class="editor-actions"><button class="button" id="append">${item.kind==='count'?'+ Place another':'Redraw line'}</button><button class="button" id="trim">${selectedVertex!==null?'Remove selected point':item.kind==='count'?'Remove last point':'Trim last segment'}</button></div><p class="small">${item.kind==='count'?'Drag markers to relocate. Changing quantity adds or removes visible markers.':'Drag endpoints or vertices to trim. Changing quantity resizes the visible line from its first point.'}</p>`;
 for(const [id,key] of [['edit-label','label'],['edit-group','group'],['edit-note','note']])$('#'+id).oninput=e=>mutate(()=>{item[key]=e.target.value;item.source='manual';});
 $('#edit-qty').oninput=e=>{const n=Number(e.target.value);if(!Number.isFinite(n)||n<=0||(item.kind==='count'&&(!Number.isInteger(n)||n>1000))){notice('Use a positive quantity (point counts must be whole numbers, up to 1,000).',true);return;}const old=quantity(item,state.scale);if(item.kind==='length'){const anchor=item.geom.points[0],ratio=n/old;const points=item.geom.points.map(p=>({x:anchor.x+(p.x-anchor.x)*ratio,y:anchor.y+(p.y-anchor.y)*ratio}));if(!old||points.some(p=>p.x<0||p.y<0||p.x>state.doc.width||p.y>state.doc.height)){log('That length would move the line outside the drawing. Redraw it instead.');render();return;}mutate(()=>{item.geom.points=points;item.source='manual';});}else{mutate(()=>{while(item.geom.points.length<n){const a=item.geom.points.at(-1);item.geom.points.push({x:Math.min(state.doc.width-10,a.x+18),y:Math.min(state.doc.height-10,a.y+12)});}item.geom.points.length=n;item.source='manual';});notice('Quantity updated. Reposition any added markers to the correct symbols.',true);}};
 $('#delete-row').onclick=()=>mutate(()=>{state.items=state.items.filter(i=>i.id!==selected);selected=null;});$('#append').onclick=()=>{setTool(item.kind);if(item.kind==='length')notice('Trace the replacement line; finish to replace the selected geometry.');};$('#trim').onclick=()=>{if(item.geom.points.length<=(item.kind==='count'?1:2))return notice('Drag an endpoint to shorten this line, or delete the whole item.',true);mutate(()=>{item.geom.points.splice(selectedVertex??item.geom.points.length-1,1);selectedVertex=null;item.source='manual';});};if(focusId?.startsWith('edit-')){const field=$('#'+focusId);field?.focus({preventScroll:true});if(cursor!==null&&field?.type!=='number')field?.setSelectionRange?.(cursor,cursor);}}
function renderOverlay(){const svg=$('#overlay');if(!state.doc)return;svg.setAttribute('viewBox',`0 0 ${state.doc.width} ${state.doc.height}`);let html='';for(const item of state.items){const color=SYSTEMS[item.group]||SYSTEMS.Pipe,active=item.id===selected;const ps=item.geom.points;if(item.kind==='length')html+=`<polyline data-item="${item.id}" points="${ps.map(p=>p.x+','+p.y).join(' ')}" fill="none" stroke="${color}" stroke-width="${active?4:2}" opacity="${selected?(active?1:.18):.75}" vector-effect="non-scaling-stroke"/><polyline data-item="${item.id}" points="${ps.map(p=>p.x+','+p.y).join(' ')}" fill="none" stroke="transparent" stroke-width="10" vector-effect="non-scaling-stroke"/>`;
 if(active&&item.source==='AI')for(const gap of item.analysis?.gaps||[])html+=`<polyline data-item="${item.id}" points="${gap.map(p=>p.x+','+p.y).join(' ')}" stroke="#dc9828" stroke-width="4" stroke-dasharray="3 3" vector-effect="non-scaling-stroke" fill="none"/>`;
 if(item.kind==='count'||active)ps.forEach((p,index)=>{html+=`<circle opacity="${selected?(active?1:.25):1}" data-item="${item.id}" data-index="${index}" cx="${p.x}" cy="${p.y}" r="${item.kind==='count'?13:8}" fill="${active?color:'white'}" fill-opacity=".85" stroke="${color}" stroke-width="2"/><text x="${p.x}" y="${p.y+4}" text-anchor="middle" font-size="12" fill="${active?'white':color}" pointer-events="none">${item.kind==='count'?index+1:''}</text>`;});}
 if(state.scale)html+=`<polyline points="${state.scale.reference.points.map(p=>p.x+','+p.y).join(' ')}" stroke="#c49620" stroke-width="2" stroke-dasharray="8 5" fill="none"/>`;
 if(draft.length){html+=`<polyline points="${draft.map(p=>p.x+','+p.y).join(' ')}" fill="none" stroke="#163f38" stroke-width="4" stroke-dasharray="8 5"/>`;draft.forEach(p=>html+=`<circle cx="${p.x}" cy="${p.y}" r="7" fill="#d7f895" stroke="#163f38" stroke-width="2"/>`);}svg.innerHTML=html;const activeItem=state.items.find(i=>i.id===selected);if($('#selection-caption')){$('#selection-caption').textContent=activeItem?'Selected: '+activeItem.label+' · '+activeItem.group:'Select a table row or drawing overlay to inspect matching geometry.';}}
function position(e){const r=$('#overlay').getBoundingClientRect();return {x:Math.max(0,Math.min(state.doc.width,(e.clientX-r.left)/r.width*state.doc.width)),y:Math.max(0,Math.min(state.doc.height,(e.clientY-r.top)/r.height*state.doc.height))};}
$('#overlay').onpointerdown=e=>{if(!state.doc||running)return;const p=position(e);if(tool==='select'){const id=e.target.dataset.item;if(!id){selected=null;render();return;}selected=id;const index=e.target.dataset.index;selectedVertex=index!==undefined?Number(index):null;if(index!==undefined){checkpoint();drag={id,index:Number(index),pointer:e.pointerId};$('#overlay').setPointerCapture(e.pointerId);}render();scrollSelectedRow();return;}if(tool==='calibrate'){draft.push(p);if(draft.length===2){$('#scale-description').textContent=`Selected span: ${pixelLength(draft).toFixed(1)} pixels. Enter the printed distance between these points.`;$('#scale-dialog').showModal();}renderOverlay();return;}if(tool==='count'){mutate(()=>{let item=state.items.find(i=>i.id===selected&&i.kind==='count');if(item){item.geom.points.push(p);item.source='manual';}else{item=newItem('count',[p],'Fixtures');state.items.push(item);selected=item.id;}});return;}draft.push(p);renderOverlay();};
$('#overlay').onpointermove=e=>{if(!drag)return;const item=state.items.find(i=>i.id===drag.id);item.geom.points[drag.index]=position(e);item.source='manual';render();const qty=$('#edit-qty');if(qty)qty.value=quantity(item,state.scale).toFixed(item.kind==='count'?0:2);};
function endDrag(){if(!drag)return;drag=null;save();render();}$('#overlay').onpointerup=endDrag;$('#overlay').onpointercancel=endDrag;
function finishLine(){if(draft.length<2||pixelLength(draft)<2)return notice('Choose at least two distinct points for a pipe run.',true);mutate(()=>{const item=state.items.find(i=>i.id===selected&&i.kind==='length');if(item){item.geom.points=[...draft];item.source='manual';}else{const created=newItem('length',[...draft]);state.items.push(created);selected=created.id;}draft=[];});setTool('select');}
$('#finish').onclick=finishLine;document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if(e.key==='Enter'&&tool==='length')finishLine();if(e.key==='Escape')setTool('select');if(e.key==='Delete'&&selected)$('#delete-row')?.click();if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();$('#undo').click();}});
function showDoc(){if(!state.doc)return;$('#empty').hidden=true;$('#sheet-wrap').hidden=false;$('#sheet-image').src=state.doc.data;$('#sheet-wrap').style.aspectRatio=`${state.doc.width}/${state.doc.height}`;$('#sheet-name').textContent=state.doc.name;$('#project-name').textContent=state.doc.name.replace(/\.[^.]+$/,'');$('#sheet-meta').textContent=`${state.doc.width} × ${state.doc.height} px`;setZoom(1);render();}
async function allowReplace(){if(!state.items.length)return true;$('#replace-dialog').showModal();return new Promise(resolve=>{const done=v=>{$('#replace-dialog').close();resolve(v);};$('#replace-cancel').onclick=()=>done(false);$('#replace-confirm').onclick=()=>done(true);$('#replace-dialog').oncancel=()=>done(false);});}
async function openImage(src,name,sample=false){const img=new Image();img.src=src;await img.decode();const factor=Math.min(1,2400/Math.max(img.width,img.height));raster.width=Math.round(img.width*factor);raster.height=Math.round(img.height*factor);const ctx=raster.getContext('2d',{willReadFrequently:true});ctx.fillStyle='white';ctx.fillRect(0,0,raster.width,raster.height);ctx.drawImage(img,0,0,raster.width,raster.height);state={...state,doc:{name,sample,width:raster.width,height:raster.height,data:raster.toDataURL('image/png')},scale:null,items:[]};selected=null;history=[];save();showDoc();setTool('select');if(factor<1)log('Drawing resized to 2,400 pixels for bounded processing. Calibrate this displayed image.');notice(sample?'Sample loaded. Select your outcomes, then calibrate the marked 10 m dimension.':'Drawing loaded. Select your outcomes, then calibrate a known dimension.');workflow?.drawingLoaded();}
async function loadSample(){if(running||!await allowReplace())return;try{pdf=null;$('#page').hidden=true;await openImage('/samples/residence-plumbing.png','Residence 01 · P-101',true);}catch(e){log('Sample could not load: '+e.message);}}
async function renderPdfPage(page){const p=await pdf.getPage(page),base=p.getViewport({scale:1}),v=p.getViewport({scale:Math.min(2.5,2400/Math.max(base.width,base.height))});const lib=await import('pdfjs-dist');const evidence=await extractPdfEvidence(p,v,await pdf.getOptionalContentConfig(),lib.OPS);const canvas=document.createElement('canvas');canvas.width=Math.ceil(v.width);canvas.height=Math.ceil(v.height);await p.render({canvasContext:canvas.getContext('2d'),viewport:v}).promise;await openImage(canvas.toDataURL('image/png'),pdf.fileName+' · page '+page);state.doc.pdfEvidence=evidence;state.doc.pdfPage=page;save();pdfPage=page;}
async function loadFile(file){if(!file||running)return;if(file.size>30*1024*1024)return log('This file exceeds 30 MB. Export a smaller sheet and try again.');if(!['application/pdf','image/png','image/jpeg','image/webp'].includes(file.type))return log('Unsupported file. Choose PDF, PNG, JPEG or WebP.');if(!await allowReplace())return;notice('Opening drawing locally…');try{if(file.type==='application/pdf'){const lib=await import('pdfjs-dist');lib.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).href;pdf=await lib.getDocument({data:await file.arrayBuffer(),isEvalSupported:false}).promise;pdf.fileName=file.name;$('#page').innerHTML=Array.from({length:pdf.numPages},(_,i)=>`<option value="${i+1}">Page ${i+1} / ${pdf.numPages}</option>`).join('');$('#page').hidden=pdf.numPages===1;await renderPdfPage(1);if(pdf.numPages>1)log('Multi-page PDF opened. Takeoff and calibration apply to one page at a time; export before switching pages.',false);}else{const url=URL.createObjectURL(file);try{await openImage(url,file.name);pdf=null;$('#page').hidden=true;}finally{URL.revokeObjectURL(url);}}}catch(e){log('The drawing could not be opened: '+e.message);}}
$('#page').onchange=async e=>{const n=Number(e.target.value);if(await allowReplace()){try{await renderPdfPage(n);}catch(err){log('Could not render PDF page: '+err.message);}}else e.target.value=pdfPage;};
function setZoom(z){zoom=Math.max(.5,Math.min(8,z));$('#sheet-wrap').style.width=`${zoom*100}%`;$('#zoom-label').textContent=Math.round(zoom*100)+'%';}
let runSequence=0;
function stopRun(){runSequence++;worker?.terminate();worker=null;clearTimeout(runTimer);clearInterval(elapsedTimer);running=false;$('#progress-wrap').hidden=true;$('#run').textContent='✧  Run takeoff';render();}
async function confirmCalculation(){if(!state.items.length)return true;$('#rerun-dialog').showModal();return new Promise(resolve=>{const finish=v=>{$('#rerun-dialog').close();resolve(v);};$('#rerun-cancel').onclick=()=>finish(false);$('#rerun-confirm').onclick=()=>finish(true);$('#rerun-dialog').oncancel=()=>finish(false);});}
function applyDetection(d,started){
 checkpoint();state.items=[];const numbering={};const numbered=(label)=>label+' · '+String(numbering[label]=(numbering[label]||0)+1).padStart(2,'0');
 if(state.outcomes.includes('count'))for(const p of d.points){const a=p.analysis||{method:d.backend==='Heuristic'?'Color component rules':'ONNX color-symbol classifier',classification:p.label,evidence:`A compact connected region matched the configured ${p.label} color; small connected regions (12–2,999 pixels) are retained. Runtime: ${d.backend}.`,confidence:'Color-distance threshold · not semantic confidence',limitations:'Demonstration palette only. Similar colors are not proof of a plumbing symbol.'};state.items.push({...newItem('count',[{x:p.x,y:p.y}],/valve/i.test(p.label)?'Valves':/cleanout/i.test(p.label)?'Cleanouts':/hydrant/i.test(p.label)?'Hydrants':'Fixtures',numbered(p.label),'AI'),analysis:a});}
 if(state.outcomes.includes('length'))for(const r of d.runs){const a=r.analysis||{method:'Colored raster centerline',classification:r.group+' pipe segment',evidence:`A straight band of pixels matched the configured ${r.group} palette. Parallel pixels collapsed to a centerline; minimum span 28 pixels, maximum bridged raster gap 2 pixels.`,confidence:'Palette assumption · not semantic confidence',limitations:'For compatible colored drawings only. Check the legend; dashed gaps, bends and occlusions may fragment or shorten the run.'};state.items.push({...newItem('length',r.points,r.group,numbered(r.group+' pipe segment'),'AI'),analysis:a});}
 state.lastRun={backend:d.backend,elapsed:(performance.now()-started)/1000,points:d.points.length,runs:d.runs.length,coverage:d.coverage,warning:d.backend.startsWith('PDF')?'Label-based counts; unlabelled valves/cleanouts remain unmeasured. Regular dash joins are marked; curves and irregular gaps are excluded. Check schematic runs.':'Demo-color recognition only; not a general plumbing detector.'};
 selected=null;save();stopRun();workflow?.go('results');$('#backend').textContent=d.backend;
 log(`Completed in ${state.lastRun.elapsed.toFixed(1)} s · ${d.points.length} point suggestions and ${d.runs.length} pipe segments.`,false);
 if(!d.points.length&&!d.runs.length)log('No supported elements found. The worksheet is empty; no example quantities were substituted. Use manual tools or a suitable trained model.');
}
async function run(){
 if(!state.scale||!$('#ai-enabled').checked||running||!await confirmCalculation())return;
 running=true;render();const token=++runSequence;$('#progress-wrap').hidden=false;$('#progress').value=0;$('#run').textContent='Processing drawing…';const started=performance.now();let progressMessage='Preparing drawing';
 const progress=d=>{$('#progress').value=d.progress;progressMessage=d.message;$('#progress-text').textContent=progressMessage;if(d.backend)$('#backend').textContent=d.backend;};
 elapsedTimer=setInterval(()=>{$('#progress-text').textContent=progressMessage+' · '+((performance.now()-started)/1000).toFixed(0)+'s';},500);
 runTimer=setTimeout(()=>{if(token!==runSequence)return;stopRun();log('Calculation exceeded 180 seconds and was stopped. Existing quantities are preserved. No fallback results were inserted.');},180000);
 try{
 const configured=$('#model-mode').value,mode=configured==='auto'?(state.doc.pdfEvidence||state.doc.realPlan?'pdf':'sample'):configured;
 if(mode==='pdf'){
  progress({progress:10,message:'Reading PDF labels and named CAD layers…',backend:'PDF rules · CPU'});
  let evidence=state.doc.pdfEvidence;
  if(!evidence&&state.doc.realPlan){const lib=await import('pdfjs-dist');lib.GlobalWorkerOptions.workerSrc=new URL('pdfjs-dist/build/pdf.worker.min.mjs',import.meta.url).href;const doc=await lib.getDocument({url:'/samples/real-plan/residential-asbuilt-p1.pdf',isEvalSupported:false}).promise;try{const page=await doc.getPage(1),base=page.getViewport({scale:1});evidence=await extractPdfEvidence(page,page.getViewport({scale:state.doc.width/base.width}),await doc.getOptionalContentConfig(),lib.OPS);}finally{await doc.destroy();}}
  if(token!==runSequence)return;
  if(!evidence)throw new Error('No PDF text/layer data available. Upload the original vector PDF; a raster image cannot supply CAD layers.');
  progress({progress:65,message:'Matching labels and extracting open pipe strokes…'});
  await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
  if(token!==runSequence)return;
  const result=analyzePdf(evidence,{width:state.doc.width,height:state.doc.height,countArea:$('#count-area').value,pipeArea:$('#pipe-area').value,bridgeDashes:$('#bridge-dashes').checked});
  applyDetection(result,started);return;
 }
 const img=new Image();img.src=state.doc.data;await img.decode();if(token!==runSequence)return;raster.width=state.doc.width;raster.height=state.doc.height;const ctx=raster.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0);const pixels=ctx.getImageData(0,0,raster.width,raster.height).data;
 worker=new Worker(new URL('./engine.worker.js',import.meta.url),{type:'module'});
 worker.onerror=e=>{if(token!==runSequence)return;stopRun();log('Detection worker failed: '+e.message+'. Existing quantities are preserved.');};
 worker.onmessage=({data:d})=>{if(token!==runSequence)return;if(d.type==='progress')progress(d);if(d.type==='warning')log(d.message);if(d.type==='error'){stopRun();log(d.message);}if(d.type==='done')applyDetection(d,started);};
 worker.postMessage({width:raster.width,height:raster.height,pixels:pixels.buffer,mode,modelUrl:$('#model-url').value,labels:$('#model-labels').value.split(',').map(s=>s.trim()).filter(Boolean)},[pixels.buffer]);
 }catch(e){if(token!==runSequence)return;stopRun();log('Calculation failed: '+e.message+' Existing quantities are preserved.');}
}
function download(format){if(!state.scale||!state.items.length)return;const data=report(state.items.map(i=>({...i,note:explanationNote(i,state.scale)})),state.scale),blob=new Blob([format==='csv'?csv(data):JSON.stringify(data,null,2)],{type:format==='csv'?'text/csv;charset=utf-8':'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ArchiQuant-'+new Date().toISOString().slice(0,10)+'.'+format;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);notice(format.toUpperCase()+' report downloaded. Quantities are draft plan measurements requiring review.');}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{if(['count','length'].includes(b.dataset.tool)){selected=null;selectedVertex=null;}setTool(b.dataset.tool);render();});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());for(const id of ['sample','empty-sample'])$('#'+id).onclick=loadSample;for(const id of ['upload','empty-upload'])$('#'+id).onclick=()=>{if(!running)$('#file').click();};$('#file').onchange=e=>{loadFile(e.target.files[0]);e.target.value='';};$('#viewport').ondragover=e=>{e.preventDefault();};$('#viewport').ondrop=e=>{e.preventDefault();loadFile(e.dataTransfer.files[0]);};
for(const id of ['scope-nav','scope-button'])$('#'+id).onclick=()=>{if(!running)$('#scope-dialog').showModal();};$('#workspace-nav').onclick=()=>$('#viewport').focus();$('#scope-continue').onclick=()=>{const outcomes=['count','length'].filter(k=>$('#out-'+k).checked);if(!outcomes.length)return log('Select at least one calculation outcome.');state.outcomes=outcomes;save();$('#scope-dialog').close();if(state.doc&&!state.scale)setTool('calibrate');};$('#settings').onclick=()=>{if(!running)$('#settings-dialog').showModal();};$('#model-mode').onchange=e=>{$('#custom-settings').hidden=e.target.value!=='custom';};$('#save-scale').onclick=()=>{try{const scale=makeScale(draft[0],draft[1],Number($('#real-distance').value),$('#scale-unit').value);mutate(()=>{state.scale=scale;});$('#scale-dialog').close();setTool('select');notice('Scale confirmed. Run takeoff or add measurements with the manual tools.');}catch(e){log(e.message);}};$('#scale-dialog').addEventListener('close',()=>{draft=[];renderOverlay();});$('#ai-enabled').onchange=()=>{if(running)stopRun();render();};$('#run').onclick=()=>run();$('#cancel').onclick=()=>{stopRun();notice('Detection canceled. Existing measurements are preserved.');};$('#undo').onclick=()=>{if(running||!history.length)return;state=JSON.parse(history.pop());selected=null;draft=[];save();render();};$('#zoom-in').onclick=()=>setZoom(zoom+.25);$('#zoom-out').onclick=()=>setZoom(zoom-.25);$('#fit').onclick=()=>setZoom(1);$('#toggle-overlay').onclick=()=>{$('#overlay').classList.toggle('muted-overlay');};$('#add-item').onclick=()=>{selected=null;setTool('count');render();};$('#export-csv').onclick=()=>download('csv');$('#export-json').onclick=()=>download('json');$('#warnings').onclick=()=>{$('#activity-list').innerHTML=errors.length?errors.map(e=>`<p class="activity-entry"><small>${esc(e.time)} · ${e.warning?'NOTICE':'STATUS'}</small>${esc(e.message)}</p>`).join(''):'<p>No processing notices in this session.</p>';$('#activity-dialog').showModal();};$('#clear-session').onclick=()=>{try{localStorage.removeItem('archiquant-v1');notice('Saved session removed from this device. Your current drawing stays open.');$('#activity-dialog').close();}catch(e){log('Could not clear saved session: '+e.message);}};
window.addEventListener('error',e=>log('Unexpected error: '+e.message));window.addEventListener('unhandledrejection',e=>log('Unexpected operation failure: '+(e.reason?.message||e.reason)));
try{const raw=localStorage.getItem('archiquant-v1');if(raw){const s=JSON.parse(raw);if(!s.doc||!Array.isArray(s.items)||s.items.some(i=>!['count','length'].includes(i.kind)||!Array.isArray(i.geom?.points)||i.geom.points.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.y))))throw new Error('Invalid saved geometry');state=s;showDoc();notice('Restored your last drawing and quantities from this device.');}}catch(e){log('Saved session could not be restored: '+e.message);}render();

$('.panel-heading').insertAdjacentHTML('afterend','<div id="selection-caption">Select a table row or drawing overlay to inspect matching geometry.</div>');
workflow=createWorkflow({getState:()=>state,isRunning:()=>running,notice,save,render,showDoc,setTool,loadSample,loadFile,openImage,allowReplace,focusPoints,fit:()=>{setZoom(1);$('#viewport').scrollTo(0,0);},reset:s=>{state=s;selected=null;selectedVertex=null;draft=[];history=[];pdf=null;$('#page').hidden=true;$('#ai-enabled').checked=true;render();}});

let resizeFocus;window.addEventListener('resize',()=>{clearTimeout(resizeFocus);resizeFocus=setTimeout(()=>{const item=state.items.find(i=>i.id===selected);if(item&&workflow?.stage==='results'){focusPoints(item.geom.points);scrollSelectedRow();}},150);});
