const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const steps=['projects','drawing','scale','calculate','results'];
export function createWorkflow(api){
 let stage='projects',index=[],memory=new Map(),pendingExample=null;
 try{index=JSON.parse(localStorage.getItem('archiquant-project-index')||'[]');if(!Array.isArray(index))index=[];}catch{api.notice('The saved project list could not be read. Your open drawing remains available.',true);}
 const panel=document.createElement('div');panel.id='workflow-pages';panel.innerHTML=`
 <section id="projects-page" class="workflow-page"><div class="page-lead"><div><span class="eyebrow">YOUR WORKSPACE</span><h2>Projects</h2><p>Start a takeoff or pick up where you left off.</p></div><button class="button primary" id="new-project">+ Create project</button></div><div id="project-grid" class="project-grid"></div></section>
 <section id="drawing-page" class="workflow-page" hidden><div class="page-lead"><div><span class="eyebrow">STEP 01 / DRAWING & SCOPE</span><h2>Give your project a drawing.</h2><p>Choose a sheet, then decide which quantities to calculate.</p></div></div><div class="setup-grid"><div class="upload-surface" id="drawing-drop"><div id="drawing-preview-empty"><span class="upload-symbol">↥</span><h3>Drop your construction drawing</h3><p>PDF, PNG, JPG or WebP · up to 30 MB</p></div><img id="drawing-preview" alt="Selected project drawing preview" hidden><strong id="drawing-choice"></strong><button class="button primary" id="choose-project-file">Choose drawing</button><button class="text-button" id="choose-example">Choose an example instead →</button></div><div id="scope-panel" class="scope-panel"></div></div><div class="stage-navigation"><button class="button" id="drawing-back">← Projects</button><span id="drawing-validation"></span><button class="button primary" id="drawing-next">Set scale →</button></div></section>
 <section id="calibration-intro" class="calibration-intro" hidden><div><span class="eyebrow">STEP 02 / SCALE</span><h2>Turn drawing distances into real measurements.</h2><p id="calibration-help">Click two ends of a known dimension, then enter its real length.</p></div><div class="calibration-actions"><button class="button" id="locate-reference" hidden>Find scale bar</button><button class="button" id="recalibrate">↔ Pick two points</button></div></section>
 <section id="calculation-page" class="workflow-page" hidden><div class="calculation-card"><span class="eyebrow">STEP 03 / CALCULATION</span><div id="processing-orbit" class="processing-orbit">⌁</div><h2 id="calculation-title">Ready to calculate.</h2><p id="calculation-description">The drawing stays on your device. Review the proposed quantities in the next step.</p><div id="calculation-summary"></div><div id="run-destination"></div><button class="button full" id="manual-results">Continue with manual takeoff →</button><button class="button primary full" id="reference-results" hidden>Calculate the traced example →</button><p id="reference-disclaimer" class="small" hidden>Uses prepared, manually traced geometry on the real sheet. This is not AI recognition.</p><button class="text-button" id="calculation-back">← Back to scale</button></div></section>
 <div id="scale-navigation" class="stage-navigation" hidden><button class="button" id="scale-back">← Drawing & scope</button><span id="calibration-status">Calibration required</span><button class="button primary" id="scale-next" disabled>Continue to calculation →</button></div>
 <div id="results-context" class="results-context" hidden><span id="results-basis"></span><div><button class="button" id="results-recalculate">Recalculate</button><button class="button" id="results-scale">Check scale</button><button class="button" id="results-drawing">Change drawing</button></div></div>`;
 $('.workbench').before(panel);
 const scope=$('#scope-dialog');for(const child of [...scope.children])if(child.matches('.scope-card,.outcomes,.future-scopes'))$('#scope-panel').append(child);
 $('#scope-panel').insertAdjacentHTML('afterbegin','<span class="eyebrow">CALCULATION SCOPE</span><h3>What would you like to measure?</h3>');
 $('#run-destination').append($('.run-box'));
 $('.workbench').before($('#results-context'));
 $('.workbench').after($('#scale-navigation'));
 $('.workbench').prepend($('.worksheet-panel'));
 $('.steps').innerHTML=steps.map((s,i)=>`<button data-stage="${s}"><b>${i+1}</b>${['Projects','Drawing & scope','Set scale','Calculate','Results'][i]}</button>${i<4?'<i></i>':''}`).join('');
 $('.project-bar h1').textContent='A workspace for every takeoff.';
 $('.header-actions').insertAdjacentHTML('afterbegin','<button class="button" id="all-projects">← Projects</button>');
 $('.shell').insertAdjacentHTML('beforeend',`<dialog id="create-project-dialog"><div class="dialog-top"><span class="eyebrow">NEW TAKEOFF</span><button class="close" id="close-project-dialog" aria-label="Close create project">×</button></div><h2>Create a project</h2><label>Project name<input id="new-project-name" placeholder="e.g. Riverside residence · plumbing" maxlength="100"></label><p class="small">Saved locally on this device. You can reopen it from Projects.</p><button class="button primary full" id="create-project-confirm">Create project →</button></dialog>
 <dialog id="examples-dialog" class="examples-dialog"><div class="dialog-top"><span class="eyebrow">EXAMPLE DRAWINGS</span><button class="close" id="close-examples" aria-label="Close examples">×</button></div><h2>Start with an example</h2><div class="example-options"><article><img src="/samples/real-plan/residential-asbuilt-p1.png" alt="Real monochrome residential plumbing drawing"><span class="eyebrow">REAL AS-BUILT / P-1</span><h3>Residential water & drainage</h3><p>Two plumbing views, fixture tags and sized routes. Includes a prepared takeoff to inspect after calibration.</p><button class="button primary full" id="example-real">Use real drawing</button><a href="/samples/real-plan/residential-asbuilt-p1.pdf" target="_blank" rel="noopener">View original PDF ↗</a></article><article><img src="/samples/residence-plumbing.png" alt="Colored sample-symbol demonstration plan"><span class="eyebrow">DETECTOR DEMONSTRATION</span><h3>Residential sample</h3><p>A synthetic sheet for testing the bundled on-device detector and editing tools.</p><button class="button full" id="example-demo">Use detector sample</button></article></div></dialog>`);
 function metadata(s){return {id:s.projectId,name:s.projectName,updatedAt:s.updatedAt,docName:s.doc?.name||'',rows:s.items.length,hasScale:!!s.scale,stage:s.lastStage||'drawing',thumbnail:s.doc?.data?.startsWith('/')?s.doc.data:null};}
 function persist(s){if(!s.projectId)return; s.updatedAt=new Date().toISOString();memory.set(s.projectId,JSON.parse(JSON.stringify(s)));const m=metadata(s),i=index.findIndex(p=>p.id===m.id);if(i<0)index.unshift(m);else index[i]=m;try{localStorage.setItem('archiquant-project-'+s.projectId,JSON.stringify(s));localStorage.setItem('archiquant-project-index',JSON.stringify(index));}catch{api.notice('This project is open in memory, but browser storage is full. Export before closing the tab.',true);}}
 function drawProjects(){ $('#project-grid').innerHTML=`<button class="new-project-card" id="new-project-card"><span>+</span><strong>New project</strong><small>Upload a plan and start measuring</small></button>`+index.map(p=>`<button class="project-card" data-project="${p.id}"><div class="project-thumbnail">${p.thumbnail?`<img src="${escape(p.thumbnail)}" alt="">`:'<span>▧</span>'}<span class="project-badge">${p.rows&&p.hasScale?'Ready to review':p.docName?'In progress':'New project'}</span></div><div class="project-card-copy"><strong>${escape(p.name)}</strong><span>${escape(p.docName||'No drawing selected')}</span><small>${p.rows} worksheet rows · ${new Date(p.updatedAt).toLocaleDateString()}</small></div></button>`).join('');$('#new-project-card').onclick=newProject;document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.project));}
 function newProject(){if(api.isRunning())return;$('#new-project-name').value='';$('#create-project-dialog').showModal();$('#new-project-name').focus();}
 function createProject(name){api.reset({projectId:crypto.randomUUID(),projectName:name,updatedAt:new Date().toISOString(),doc:null,scale:null,items:[],outcomes:['count','length'],lastStage:'drawing'});pendingExample=null;persist(api.getState());go('drawing');api.notice('Project created. Add a drawing and choose the quantities you need.');}
 function openProject(id){if(api.isRunning())return;try{const s=memory.get(id)||JSON.parse(localStorage.getItem('archiquant-project-'+id));if(!s)throw new Error('No saved drawing found');api.reset(s);pendingExample=null;api.showDoc();go(s.items.length&&s.scale?'results':s.scale?'calculate':s.doc?'scale':'drawing');api.notice('Opened '+s.projectName+'. All saved measurements are available.');}catch(e){api.notice('Could not open this project: '+e.message,true);}}
 function go(next){if(api.isRunning()&&next!==stage){api.notice('Cancel the calculation before changing steps.',true);return;}const s=api.getState();if(next!=='projects'&&!s.projectId)return newProject();if(['scale','calculate','results'].includes(next)&&!s.doc)return api.notice('Choose a drawing first.',true);if(['calculate','results'].includes(next)&&!s.scale)return api.notice('Confirm the scale before continuing.',true);stage=next;if(next!=='projects'){s.lastStage=next;persist(s);}document.body.dataset.stage=next;$('#projects-page').hidden=next!=='projects';$('#drawing-page').hidden=next!=='drawing';$('#calibration-intro').hidden=next!=='scale';$('#calculation-page').hidden=next!=='calculate';$('.workbench').hidden=!['scale','results'].includes(next);$('#scale-navigation').hidden=next!=='scale';$('#results-context').hidden=next!=='results';$('.project-actions').hidden=next==='projects';$('#all-projects').hidden=next==='projects';$('#sample').hidden=next!=='drawing';$('#upload').hidden=next!=='drawing';$('.steps').hidden=next==='projects';$('.project-bar').hidden=next==='projects';$('#notice').hidden=next==='projects';$('.worksheet-panel').hidden=next!=='results';$('.project-bar h1').textContent=({drawing:'Drawing & calculation scope',scale:'Set the drawing scale',calculate:'Calculate your quantities',results:'Review your takeoff'})[next]||'Projects';$('#project-name').textContent=s.projectName||'All projects';if(next==='projects')drawProjects();if(next==='scale'){api.setTool('calibrate');api.fit();}if(next==='results'){api.setTool('select');api.render();api.fit();}refresh();window.scrollTo({top:0,behavior:'instant'});}
 function refresh(){const s=api.getState();$('#project-name').textContent=stage==='projects'?'All projects':s.projectName||'Untitled project';$('#drawing-preview').hidden=!s.doc;$('#drawing-preview-empty').hidden=!!s.doc;if(s.doc){$('#drawing-preview').src=s.doc.data;$('#drawing-choice').textContent=s.doc.name;}else $('#drawing-choice').textContent='';$('#drawing-next').disabled=!s.doc;$('#scale-next').disabled=!s.scale;$('#calibration-status').textContent=s.scale?`Scale confirmed · ${s.scale.pixelsPerMeter.toFixed(2)} pixels per meter`:'Choose two points to confirm the scale';$('#locate-reference').hidden=!s.doc?.reference;$('#calibration-help').textContent=s.doc?.realPlan?'Find the printed 0–4 m scale bar at the lower left. Click its two endpoints and enter 4 meters.':s.doc?.sample?'Click the endpoints of the lower dimension marked 10 m, then confirm 10 meters.':'Click two ends of a known dimension, then enter its real length.';$('#real-distance').value=s.doc?.realPlan?'4':'10';$('#calculation-summary').innerHTML=s.doc?`<strong>${escape(s.doc.name)}</strong><span>${s.outcomes.map(k=>k==='count'?'Point counts':'Pipe lengths').join(' + ')} · ${s.scale?s.scale.pixelsPerMeter.toFixed(2)+' px/m':'Scale pending'}</span>`:'';$('#reference-results').hidden=!s.doc?.exampleUrl||api.isRunning();$('#reference-disclaimer').hidden=!s.doc?.exampleUrl;$('#manual-results').hidden=api.isRunning();$('#calculation-back').hidden=api.isRunning();$('#calculation-title').textContent=api.isRunning()?'Calculating your takeoff…':'Ready to calculate.';$('#processing-orbit').classList.toggle('running',api.isRunning());$('#results-basis').innerHTML=s.doc?.realPlan?`<strong>Real drawing · P-1</strong> <span>Manual reference · visible supply and sanitary routes only. Excludes gas, storm drains, vertical runs and fittings.</span><a href="/samples/real-plan/residential-asbuilt-p1.pdf" target="_blank" rel="noopener">Original sheet ↗</a>`:'<strong>Live quantities</strong><span>Select a table row or an overlay to inspect the matching measurement.</span>';document.querySelectorAll('[data-stage]').forEach(b=>{b.classList.toggle('current',b.dataset.stage===stage);b.classList.toggle('complete',steps.indexOf(b.dataset.stage)<steps.indexOf(stage));b.disabled=api.isRunning()||(b.dataset.stage==='scale'&&!s.doc)||(['calculate','results'].includes(b.dataset.stage)&&!s.scale);});}
 async function realExample(){if(!api.getState().projectId)createProject('Residential as-built · P-1');if(!await api.allowReplace())return;try{const response=await fetch('/samples/real-plan/example.json');if(!response.ok)throw new Error('Example manifest unavailable');const example=await response.json();await api.openImage(example.image,example.title,false);const s=api.getState();s.doc={...s.doc,data:example.image,realPlan:true,reference:example.reference,exampleUrl:'/samples/real-plan/example.json',sourceUrl:example.sourceUrl};pendingExample=example;api.save();api.showDoc();$('#examples-dialog').close();go('drawing');api.notice('Real P-1 drawing loaded. Confirm the scope, then use the printed 4 m scale bar.');}catch(e){api.notice('Could not load the real example: '+e.message,true);}}
 async function calculateReference(){if(!api.getState().scale)return;$('#reference-results').disabled=true;$('#processing-orbit').classList.add('running');$('#calculation-title').textContent='Calculating the traced geometry…';try{const s=api.getState();const example=pendingExample||await fetch(s.doc.exampleUrl).then(r=>{if(!r.ok)throw new Error('Reference data unavailable');return r.json();});await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));s.items=structuredClone(example.items).filter(i=>s.outcomes.includes(i.kind));s.resultBasis='prepared-reference';api.save();api.render();go('results');api.notice('Worked example calculated from prepared manual traces and your scale. The model did not detect these items.');}catch(e){api.notice('Example calculation failed: '+e.message,true);}finally{$('#reference-results').disabled=false;$('#processing-orbit').classList.remove('running');}}
 function drawingLoaded(){go('drawing');}
 function focusReference(){const r=api.getState().doc?.reference;if(!r)return;api.focusPoints(r.points,5);api.setTool('calibrate');}
 function focusDrawing(points){api.focusPoints(points);}
 $('#new-project').onclick=newProject;$('#close-project-dialog').onclick=()=>$('#create-project-dialog').close();$('#create-project-confirm').onclick=()=>{const name=$('#new-project-name').value.trim();if(!name){$('#new-project-name').focus();return;}$('#create-project-dialog').close();createProject(name);};$('#new-project-name').onkeydown=e=>{if(e.key==='Enter')$('#create-project-confirm').click();};$('#all-projects').onclick=()=>go('projects');$('#workspace-nav').onclick=()=>go('projects');$('#scope-nav').onclick=()=>go('drawing');$('#scope-button').onclick=()=>go('drawing');$('#drawing-back').onclick=()=>go('projects');$('#scale-back').onclick=()=>go('drawing');$('#drawing-next').onclick=()=>{const outcomes=['count','length'].filter(k=>$('#out-'+k).checked);if(!outcomes.length){$('#drawing-validation').textContent='Select at least one outcome.';return;}api.getState().outcomes=outcomes;$('#drawing-validation').textContent='';api.save();go('scale');};$('#scale-next').onclick=()=>go('calculate');$('#recalibrate').onclick=()=>api.setTool('calibrate');$('#locate-reference').onclick=focusReference;$('#calculation-back').onclick=()=>go('scale');$('#manual-results').onclick=()=>{go('results');api.notice('Manual takeoff. Use Count or Length on the drawing to add measurements.');};$('#reference-results').onclick=calculateReference;$('#results-recalculate').onclick=()=>go('calculate');$('#results-scale').onclick=()=>go('scale');$('#results-drawing').onclick=()=>go('drawing');document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>go(b.dataset.stage));$('#choose-project-file').onclick=()=>$('#file').click();const chooseExamples=()=>$('#examples-dialog').showModal();$('#choose-example').onclick=chooseExamples;$('#sample').onclick=chooseExamples;$('#empty-sample').onclick=chooseExamples;$('#close-examples').onclick=()=>$('#examples-dialog').close();$('#example-real').onclick=realExample;$('#example-demo').onclick=async()=>{await api.loadSample();$('#examples-dialog').close();go('drawing');};$('#drawing-drop').ondragover=e=>e.preventDefault();$('#drawing-drop').ondrop=e=>{e.preventDefault();api.loadFile(e.dataTransfer.files[0]);};$('#clear-session').textContent='Remove saved copy of this project';$('#clear-session').onclick=()=>{const s=api.getState();if(!s.projectId)return;try{localStorage.removeItem('archiquant-project-'+s.projectId);localStorage.removeItem('archiquant-v1');index=index.filter(p=>p.id!==s.projectId);localStorage.setItem('archiquant-project-index',JSON.stringify(index));$('#activity-dialog').close();api.notice('Saved copy removed. The open project remains in memory; further edits will save it again.');}catch(e){api.notice(e.message,true);}};
 const current=api.getState();if(current.doc&&!current.projectId){current.projectId=crypto.randomUUID();current.projectName=current.doc.name;current.lastStage=current.items.length?'results':'scale';persist(current);}go('projects');
 return {persist,refresh,go,drawingLoaded,focusDrawing,get stage(){return stage;}};
}
